### ISSUE TITLE
JSONデータを検索出来るようにする

### ISSUE THREAD

**Issue by azu** [jser/jser.info#10]
リポジトリにあるJSONから検索出来るようにする。

全部がJSONになってれば、クライアントサイドだけでも検索は実装できるはず(JSONのサイズが心配だけど)
- [x] [過去のデータも全てJSONに変換する · Issue #9 · azu/jser.info](https://github.com/azu/jser.info/issues/9)

**Comment by azu** [comment]
RJSONで圧縮すれば、少し容量減らせるかなと思ったけど、1MBぐらいのJSONが950KBぐらいにしかならなかった。

**Comment by e-jigsaw** [comment]
http://msgpack.org/ はどうですか

**Comment by azu** [comment]
Github Pagesだと Content-Encoding:"gzip" がかかってるので、
元ファイルを圧縮しておくの意味はそこまで出ないかもしれないですね。

意外とJSONそのまま使ってるのが多い気がするので、気にならないものなのかもしれないですね。
- http://component.io/
- http://bower.io/search/

**Comment by e-jigsaw** [comment]
なるほど〜

**Comment by azu** [comment]
NYTimesが面白そうなものをだしてた
- [NYTimes/pourover](https://github.com/NYTimes/pourover)

[Tamper](https://github.com/nytimes/tamper/)というやつでデータのシリアライズをして使うみたい。GzipしたJSONについても書かれてる

**Comment by azu** [comment]
[Firebase - Build Realtime Apps](https://www.firebase.com/) とか使うの面白そう

**Comment by azu** [comment]
GitHub検索と https://realtime.jser.info あるからとりあえずいいか
