### ISSUE TITLE
JSer.infoの記事の外部リンクがタブで開かない

### ISSUE THREAD

**Issue by k35o** [jser/jser.info#121]
意図的な挙動でしたらすみません🙏

[#139](https://github.com/jser/jser.github.io/issues/139) でリンクをタブで開くようにするような変更が行われていましたが、[GAからGTMへの置き換え](https://github.com/jser/jser.github.io/commit/8d3c6697ec321f182f78b0f67857b03532bf913f)によって変更が取り消されているみたいです。

個人的には外部リンクになっていると、読んでいたページに戻りやすいので嬉しいです。

**Comment by azu** [comment]
ありがとうございます。意図しない変更なので戻した方が良さそうですね

**Comment by k35o** [comment]
@azu 
折角なのでPR立てたいです。

既存通り`google_analytics.html`に記述した方が良いですかね？
GTMに関係ないので別の箇所においても良いのかなと思いました。

**Comment by azu** [comment]
別で良いと思います。
