### ISSUE TITLE
不要そうなファイルがある

### ISSUE THREAD

**Issue by Layzie** [jser/jser.info#16]
https://github.com/azu/jser.info/blob/gh-pages/data/2011/06/index%20(thinkpad%20%E4%B8%8A%E3%81%AE%E5%95%8F%E9%A1%8C%E3%81%AE%E3%81%82%E3%82%8B%E3%82%B3%E3%83%92%E3%82%9A%E3%83%BC%202011-06-02).html

こちらなんですが、不要そうに見えました。(自分のマシンで表示が変になってたんで、気付いた次第です)

必要だったらごめんなさい。

**Comment by azu** [comment]
Dropboxで衝突してできたゴミですね…

**Comment by azu** [comment]
削除しましたー

``` sh
find `git rev-parse --show-toplevel` -name "*問題の*.html" -type f -print0 | xargs -0 rm
```

**Comment by Layzie** [comment]
ありがとうございます! :+1:
