### ISSUE TITLE
Jekyllベースのブログへの移行を検討

### ISSUE THREAD

**Issue by azu** [jser/jser.info#21]
最近、[Web Scratch](http://efcl.info/)の方をJekyll + Github pagesに移行して、基本的な移行やJekyllのビルド時間は問題ない事がわかったので、JSer.infoについても検討する
### メリット
- Github pagesは早い(CDNとか効くしビルドも意外と早い)
- ユーザーがPull Requestを送りやすくなる
  - 直接記事に対してもPull Requestができるようになる
  - 今までは[JSer.info Pull Request Form](http://azu.github.io/JSer.info-tribute/)を使った限定的なものしかない
### デメリット
- 一部URLが見えなくなるかもしれない
  - Tumblrは一つの記事に2つのURL持ってる(シンプルなのとタイトル入れたやつ)
  - [Tumblr — jekyll-import • Import your old &amp; busted site to Jekyll](http://import.jekyllrb.com/docs/tumblr/) のでき次第
  - それぞれの記事は移行できると思う。
  - ストック型のブログじゃないのでそこまで気にしなくてはいいかもしれない。
- ブログエディタが使えない
  - marsedit等が使えない、けど探せば何かいいのあると思う。
  - 今のJSer.infoは既にMarkdownなのでそこまで問題ではない
- Tumblrのreblogやlikeがしにくい、Tumblr固有の機能がなくなる
  - 多分これが一番のデメリットではある
  - プラットフォーム依存の機能
### その他
- 検索は元々無いようなものなので機能面ではほぼ同レベル
- デザインを考えるのが面倒

メリットがデメリットを上回るかどうか次第な感じがします。

どうでしょうか?

:+1: or :-1:

**Comment by kyo-ago** [comment]
:+1:

// 個人的にTumblrの機能使ってないのでデメリット感じないというのがあります

**Comment by e-jigsaw** [comment]
:+1:

**Comment by azu** [comment]
仮に移行する場合は、organizationを作ってそちらでやる感じになると思うので(ドメインはアカウントに適応されるので)、
放置されてるみたいだし https://github.com/jser のアカウント使いたいですね。

[Githubでpecoのアカウントを融通してもらった件 : D-7 &lt;altijd in beweging&gt;](http://lestrrat.ldblog.jp/archives/39456399.html) みたいにメールだしてやる感じか。
ちゃんと伝わるメール書くの大変そうだ…

**Comment by haya14busa** [comment]
@azu さんはじめまして。 横から急に失礼します。

もちろん https://github.com/jser のアカウント使ってorganizationでやるのが一番よいとは思いますが、もしだめだった場合でも

> (ドメインはアカウントに適応されるので)、

これは `azu.github.io` というユーザーページにドメインを設定すると他のプロジェクトページにまですべて影響するという話で、プロジェクトページにドメインをあてる場合は他のページには影響しないという仕様になっているはずです。

ですのでこのまま azuさんのリポジトリとしても運用はできるなぁと思ったのでコメントさせていただきました。 自分も似た経験があって困ったことがあったので。

プランBとして考えていただけるとよいと思います。

一応実際の例です。

#### 両方プロジェクトページ
1. https://github.com/haya14busa/haya14busa-s-blog/tree/gh-pages
   - ドメイン変更: https://github.com/haya14busa/haya14busa-s-blog/blob/gh-pages/CNAME
   - URL: http://haya14busa.com/
2. https://github.com/haya14busa/reading-vimplugin
   - ドメイン変更: なし
   - URL: http://haya14busa.github.io/reading-vimplugin/
   - **ドメイン変更の影響なし**

**Comment by azu** [comment]
https://github.com/jser

 GitHubに連絡して空けてもらいましたー

**Comment by azu** [comment]
@haya14busa くわしい解説ありがとうございます!

**Comment by azu** [comment]
RSSは単純に移行できるとして、
Tumblrの(フォローしてる人の)ダッシュボードで追っかけてた人向けに、
最初は、[ rss to tumblr ](https://ifttt.com/recipes/15892-rss-to-tumblr)みたいな感じでTumblrにもlinkを自動postする感じが無難ですかね。
(Tumblrのフォロワーは大体400ぐらいなのでそんなに多くは無い気がするけど)

**Comment by azu** [comment]
# RESULT

皆さまの意見も参考にして、
デメリットよりメリットのほうが多そうなので、TumblrからJekyll(Github Pages)に移行しようと思います。

時期はできるだけ早くですが、7月ちょっと忙しいのでその後ぐらいかも。

後でIssueを立てていくと思いますが、細々やることあるので列挙しておきます。
1.  このリポジトリを https://github.com/jser にtransfer
   - http://azu.github.io/JSer.info-tribute/ とかパスが固定なので直す必要がある
   - リポジトリ名をdata的なのに変更するかも。(jser.info以下に配置されるので何か便利に使いたい)
   - Gitter [![Gitter chat](https://badges.gitter.im/azu/jser.info.png)](https://gitter.im/azu/jser.info) とかも移す?(自動で移る?)
2. https://github.com/jser のアイコン/ロゴが欲しい #4 
3. https://github.com/jser/jser.github.io/ を作成
4. Jekyll ブログのデザインを考える
   - なんだかんだ |本文|サイド| の2カラム が好きなのでその辺になりそう
   - もちろん作ってくれてもいいんですよ!
5. Tumblrの記事をJekyllに移す
6. CNAMEの配置 = ドメインの指すポイントの変更
7. [IFTTT](https://ifttt.com/myrecipes/personal): RSS -> Tumblr
8. 移行完了!

5からは一気にやる必要がありますが、4まではゆっくりできます。

**Comment by Layzie** [comment]
:+1:

**Comment by syoichi** [comment]
:+1:

**Comment by azu** [comment]
リポジトリを azu -> jserへ移行しました。
Gitterはリポジトリの以上に追従しないでいままでのデータ消えたようなので、
同じようにazu -> jserしたページ作りました。

[![Gitter chat](https://badges.gitter.im/jser/jser.info.png)](https://gitter.im/jser/jser.info)

**Comment by azu** [comment]
移行完了しました! :sparkles:

http://jser.info/

バグなどあったらよろしくお願い致します。
