### ISSUE TITLE
new JSer.infoのJekyllテーマ作成

### ISSUE THREAD

**Issue by azu** [jser/jser.info#24]
#21

Jekyllのテーマを作成する。

リポジトリ : https://github.com/jser/jser.github.io

Jekyllのレイアウトとして必要なのは
- [x] default(TOP)
- [x] page( ﻿http://jser.info/about みたいなページ)
- [x] post(記事)

機能として必要なのは
- [x] 検索窓(Google?、データ検索ができるまではこれでいいかな)
- タグ情報の表示
- <del>タグ一覧(カテゴリはイラない気がする)</del>
- [x] 最近の記事表示
- [x] Edit on GitHub的なの
- [x] Zenbackみたいの
- [x] コメント(これは http://efcl.info/ みたいにボタン押してから初めて読む感じしたい)

他に考えられそうな機能
- このリポジトリのdataを利用した検索
- 紹介記事についてるタグからの検索

他に必要なこと
- デザイン
- アイコン
- [x] 投稿のフォーマットの変更? #27

**Comment by azu** [comment]
とりあえず、基本的な2カラムのレイアウト作ってみた
- http://jser.github.io/
- https://github.com/jser/jser.github.io

後はこれにデザインを載せていく感じになる気がするけど、センス欲しい。。

**Comment by azu** [comment]
現在の形 http://jser.github.io/ で見れます。

何か色が足りないというか余白が余白っぽい感じがする。

``` scss
$base-color: rgb(250, 250, 250);
$main-color: rgb(20, 180, 200);
$main-sub-color: #148ac7;
$accent-color: complement($main-color);
```

タイトルの背景にメインカラー使うのどうなんだろ?

pc

![pc](https://cloud.githubusercontent.com/assets/19714/3720547/38b3a24c-1656-11e4-89e0-e4909fe2346c.png)

mobile
![mobile](https://cloud.githubusercontent.com/assets/19714/3713975/8b72a320-158e-11e4-86f6-8043675a5cd6.png)

**Comment by Layzie** [comment]
こっちでコメント良いか微妙ですけど…

http://jser.github.io/page/1/

このurlが404になるので、ページャーを1回押したあとに絶対にエラーページに飛んでしまいます。

**Comment by azu** [comment]
@Layzie 修正してみました。
Jekyllでよくあるミスパターンらしく、公式サイトにも書いてありました

http://jekyllrb.com/docs/pagination/

**Comment by Layzie** [comment]
@azu 修正ありがとうございます。ほんとだ公式にあるんですね。

**Comment by azu** [comment]
最低限必要な機能は大体つけた。
(タグ一覧あんまり意味がない機能なので入れなくても良さそう。
もっとデータを使ったツール的なものを考えたい)
- http://jser.github.io/

![ミニマムUI](https://cloud.githubusercontent.com/assets/19714/3736096/a0e3500e-172a-11e4-9d6a-615b475ba9d2.png)

efcl.info からの流用が多くて、無個性な感じがする。
もう少しアクセントがあったほうがいい気がする。

**Comment by azu** [comment]
- [x] aリンクの折り返し
- [x] mobileでgithub badgeが邪魔

**Comment by azu** [comment]
現在のテーマの様子。とりあえず最初はこんな感じでいこうと思います。
改善案は常時受付中です。

http://jser.github.io/

![result](https://cloud.githubusercontent.com/assets/19714/3788487/e3b348d0-1a68-11e4-99cc-80d9c4aabf6d.png)
