### ISSUE TITLE
ブログ記事のセマンティックを考える

### ISSUE THREAD

**Issue by azu** [jser/jser.info#27]
今の JSer.info の記事は以下みたいにblockquoteとか、元とは意味の違う使い方をしてる。
- https://gist.github.com/azu/8dd608b1b460a42a43eb

これのメリットとして、TumblrのダッシュボードやRSSでも大体似たような表示になる。
(HTMLのタグを見た目的に使うの自体変で色々アレだけど)

これは、セマンティック的にはsectionとかちゃんとつかって分けるのが正しい。
- https://gist.github.com/hail2u/656048502196ae8f2b3d/681d77ce2a3b4f1205a25d67e4a6f0e22b282e44

けど、sectionとか囲んで使うやつは[Markdownと相性が悪い](https://twitter.com/azu_re/status/492994361559236609)ので、使おうと思うと別の方法が必要になる。

Markdown的に囲みをやるには以下のようにlistを使っていくか、`----`で区切りを付けるぐらいしか無いらしい。
- https://gist.githubusercontent.com/hail2u/656048502196ae8f2b3d/raw/62a59dff28aedef36ec2099715bd233d5826dd94/blog.md
- https://twitter.com/hail2u_/status/492996451807412225

http://webplatformdaily.org/ とかがこれに[近い事](https://twitter.com/azu_re/status/492997472570986497)をやってる。

移行ついでに、この記事の書式も変えられるなら一緒に変えておきたい気がする。

**Comment by azu** [comment]
Jekyllで使えるMarkdown以外の記法で解決できたりするのが一番良さそうな気がするけど現実は厳しい。
多分GitHubのやつは用意されてるプロセッサしか使えないはず
- [Custom Markdown Processors](http://jekyllrb.com/docs/configuration/#custom-markdown-processors)

**Comment by azu** [comment]
``` markdown
- # strict mode - motivation and semantics - Constellation Scorpius #

  [http://utatane-constellation.tumblr.com/post/3711268645](http://utatane-constellation.tumblr.com/post/3711268645 "strict mode - motivation and semantics - Constellation Scorpius")
  strict modeの概念とは何か  
  static解析につながる話
```
- # strict mode - motivation and semantics - Constellation Scorpius
  
  [http://utatane-constellation.tumblr.com/post/3711268645](http://utatane-constellation.tumblr.com/post/3711268645)
  strict modeの概念とは何か  
  static解析につながる話

という書き方、

marukuとkramdownは大丈夫で、
- https://github.com/bhollis/maruku/
- http://kramdown.gettalong.org/

redcarpetはダメみたい(もしかしたらオプションで変わるのかも)
- https://github.com/vmg/redcarpet

本家も大丈夫とのこと
- https://twitter.com/hail2u_/status/493004779535085568

**Comment by azu** [comment]
ll > h1

はちゃんとセクショニングされる仕様らしい

**Comment by azu** [comment]
このセマンティックにスタイル当ててみた。
- http://jser.github.io/2014/07/26/welcome-to-jekyll/

前文で普通にliを使う事あるから、隣接セレクタ多用してるけどこんな感じなのかな

**Comment by qrg** [comment]
``` markdown
# ヘッドライン

## タイトル
[Welcome to Jekyll!](http://jser.github.io/2014/07/26/welcome-to-jekyll/)
補足本文
* 補足用リスト
* 補足用リスト

## タイトル
[新しいタブ](chrome-search://local-ntp/local-ntp.html)
補足本文
* 補足用リスト
* 補足用リスト

# ニュース
## strict mode - motivation and semantics - Constellation Scorpius
[http://utatane-constellation.tumblr.com/post/3711268645](http://utatane-constellation.tumblr.com/post/3711268645)
strict modeの概念とは何か
static解析につながる話
```

みたいなかんじだとなんか不都合あるんでしたっけ

**Comment by azu** [comment]
https://gist.github.com/azu/8dd608b1b460a42a43eb と同じで、多分スタイル的には頑張ればどうにかなりますが、以下がひとつの塊であると構造的に見つけるのが難しいという感じです。

``` markdown
## タイトル
[Welcome to Jekyll!](http://jser.github.io/2014/07/26/welcome-to-jekyll/)
補足本文

* 補足用リスト
* 補足用リスト
```

``` html
<h2 id="section">タイトル</h2>
<p><a href="http://jser.github.io/2014/07/26/welcome-to-jekyll/">Welcome to Jekyll!</a>
補足本文</p>

<ul>
  <li>補足用リスト</li>
  <li>補足用リスト</li>
</ul>
```

https://github.com/jser/jser.info/issues/27#issuecomment-50232602 の書き方の場合は、ひとつの`<li>`がひとつのブロックとみなせるので、ぎりぎり構造的になるという感じです。

``` html
<ul>
  <li>
    <h2 id="section">タイトル</h2>

    <p><a href="http://jser.github.io/2014/07/26/welcome-to-jekyll/">Welcome to Jekyll!</a></p>

    <p>補足本文</p>

    <ul>
      <li>補足用リスト</li>
      <li>補足用リスト</li>
    </ul>
  </li>
</ul>
```

Markdownだと https://gist.github.com/hail2u/656048502196ae8f2b3d/681d77ce2a3b4f1205a25d67e4a6f0e22b282e44 みたいな `<section>` で囲むという事ができない(Markdownと併用できない)ので、かなり無理矢理ということにはあまり変わらない感じです。

**Comment by azu** [comment]
後、 https://github.com/jser/jser.info/issues/27#issuecomment-50259733 のやり方だと、
通常の記事で書いた時でも多分でてきてしまうので、おそらく紹介記事と通常の記事は別のスタイルを当てられるようにしないとダメになると思います。

加えて、それ用のスタイルを当てるためにブロックの開始になる部分に目印を付ける必要がでてくるのでMarkdownじゃなくてHTMLを書く部分が増える感じですね。

```
<h2 class="目印">タイトル</h2>

[Welcome to Jekyll!](http://jser.github.io/2014/07/26/welcome-to-jekyll/)
補足本文

* 補足用リスト
* 補足用リスト
```

どっちがいいのか微妙な所

**Comment by qrg** [comment]
なるほど。

heading (h1-h6) から次の heading までは、仮に section などで囲ってなくても、その番号で暗黙的なセクションができるので、セマンティックな html としては一応問題ないという認識なんですが、プログラマブルにセクションを抽出しようとしたら、囲ってないと困りそうですね。

解決策としてリストを利用するのは妥当な気がします。

たぶん僕だったら <section> を markdown に直接書いてしまいそうですが、このあたりは記事書くときのツールでも書きやすさ、読みやすさが変わってきそうなので、どっちでも良さそう。

**Comment by azu** [comment]
Markdownらしさを追求すると、多分この辺が限界な気がする。
タグのイメージも埋め込んでるので、CSSがなくても大体同じになるというメリットはありそう。
塊として認識するために`----` で区切りを入れてる

若干コードやCSSから扱いにくいけど、Markdownとしてはこれが一番キレイな気がする。

``` markdown
----

## title
http://example.com/

![][tags] tag1, tag2, tag3

補足本文

* 補足用リスト
* 補足用リスト

[tags]: https://cloud.githubusercontent.com/assets/19714/3773066/6032c550-1908-11e4-921a-e1c7732a1da9.png "tag image"
----
```

---

## Title

http://example.com/

![](https://cloud.githubusercontent.com/assets/19714/3773066/6032c550-1908-11e4-921a-e1c7732a1da9.png) tag1, tag2, tag3

補足本文
説明文ですよーーーーーー
- 補足用リスト
- 補足用リスト

---

**Comment by azu** [comment]
https://github.com/jser/jser.info/issues/27#issuecomment-50232602 のリストベースだと、結構記事並べると良く分からない解釈されてミスが増えそうなので、
シンプルなMarkdownで済む https://github.com/jser/jser.info/issues/27#issuecomment-50831475 の方式にします。

**Comment by azu** [comment]
最終案

```
----
## [strict mode - motivation and semantics - Constellation Scorpius](http://utatane-constellation.tumblr.com/post/3711268645 "strict mode - motivation and semantics - Constellation Scorpius")
[utatane-constellation.tumblr.com/post/3711268645](http://utatane-constellation.tumblr.com/post/3711268645 "strict mode - motivation and semantics - Constellation Scorpius")

![][tags] JavaScript, ECMAScript

strict modeの概念とは何か 
static解析につながる話

----
```

![img](http://take.ms/QVnIp)

**Comment by azu** [comment]
http://jser.github.io/2014/08/02/test/

https://github.com/jser/jser.info/issues/27#issuecomment-50956961 を適応した記事。
微妙にmarginが足りてないかも?

**Comment by qrg** [comment]
こういうの好みな気がするけど、 僕だったら元の 10px から 32px くらいに設定しそう。

``` css
.post-content hr {
      :
  /*margin: 10px 2em;*/
  margin: 32px 2em;
      :
      :
```

**Comment by azu** [comment]
色々細かい調整入れましたが、HTML構造的には多分これで固定なので、Issue閉じます。

http://jser.github.io/2014/08/02/test/
