### ISSUE TITLE
JSer.infoイベントで誰かに聞きたい事リスト

### ISSUE THREAD

**Issue by azu** [jser/jser.info#36]
#31 [JSer.info 200回記念イベント](http://connpass.com/event/9067/)で誰か(参加者)に聞きたい事をメモっておきましょう。

[イベント参加者・申込者一覧](http://connpass.com/event/9067/participation/)に参加する人が載っています。

パネルディスカッションの方は[JSer.info 200回記念イベントの質問](http://www.google.com/moderator/?hl=ja#16/e=213da7)に書いておくといいですが、
懇談会(ビアバッシュ予定)で誰かに聞きたい事がある場合は、
ここにメモっておけば話が振りやすくなると思うので、そういう感じで使うといい気がします。

**Comment by azu** [comment]
https://github.com/jser/jser.info/issues/1#issuecomment-61197530

> 色々な企業のJavaScript状況について聞いて回りたい。
> どういう情報を聞いていくのが建設的なんだろ。後、聞きたい企業とかのリスト化したい。

これ関連で、企業としてJavaScript書ける人を募集といった時に、どういう人のことを言ってるのかを @teppeis さん @e-jigsaw さんとかJavaScriptっぽい企業の人に聞いてみたい。(二人とも kangax/compat-table にPRしてることに気づいた)
- いわゆるHTMLコーダーの派生系なのか(画面作る感じ)
- 複雑になってしまったJavaScriptを管理出来るような人なのか
- (JavaScriptで)アプリケーション開発する人募集なのか
- ゲーム

目的としては逆にどういう質問すれば、それが分かるようになるかを調べたい！

[JavaScript プログラマの職種は4種類くらいに分けるべき](https://gist.github.com/imaya/9592685) とかもそうだけど、
何かこういうのって実際に何するのかって聞かないとイメージが湧きにくい感じがしてる。
- [LINE Corporation | 募集職種一覧](http://linecorp.com/ja/career/position/31)

以下みたいなプロダクトベースだと分かりやすい気がする。
(でもいっぱいサービス持ってる企業だと分からない感じがする)
- [Kaizen Platform](http://kaizenplatform.com/hiring/engineer.html#frontend_engineer)
- [イマドキなフロントエンド技術で創るWebサービスの開発エンジニア（大阪） - サイボウズ株式会社の求人 - Wantedly](https://www.wantedly.com/projects/9922)

**Comment by azu** [comment]
LINE社の方がいたら、以下の記事見てて思ったけどLINE社のJavaScriptってどういう所で動いてるものかイマイチ想像出来てないから聞きたい気がする。
- [JavaScriptのクロージャ入門とECMAScript 6のletキーワードによる変数宣言 « LINE Engineers&#39; Blog](http://developers.linecorp.com/blog/ja/?p=3428)

**Comment by e-jigsaw** [comment]
@azu ES6カジュアルトークで compat-table 見たら6to5 の issue 立ってたんで @teppeis さんのリポジトリを参考に試してみたんですけど「IEで確認して」みたいなこと言われて心が折れてるとこです。

Javascript事情でいうと、僕は弊社の主流とは少し離れたところにいるのでアレなんですが、frontrendまわりのひとたちとかに聞くと結構面白いんじゃないかなとおもいました。

**Comment by azu** [comment]
> IEで確認して

@e-jigsaw おー互換性が辛い場所…
6to5自体は多分(ES5が動く)ブラウザは保証するけど、IE xxでの動作は保証するみたいな事は言ってなさそう…
https://github.com/sebmck/6to5/blob/530ad78428c859d2cc8919abad66f2490c42cb41/Makefile#L28-L31

sebmckさんはメッチャ反応早いのでissue内で、sebmckさんに@を投げて巻き込んでしまうのが早いかもしれないですね。

**Comment by e-jigsaw** [comment]
おー、そうなんですか。ちょっとmention送ってみます。thx!

**Comment by teppeis** [comment]
あー、こんなissueがあったんだ。。

@e-jigsaw Closure CompilerのときはIEで確認とかは言われなかったですね。
あのes6-tableはそれぞれの項目のテストはかなりざっくりしてるので、適当にそれっぽくtrue/falseつけちゃえば良いと思います。

**Comment by e-jigsaw** [comment]
@teppeis そうっぽいですね、mergeされないかなー。
