### ISSUE TITLE
アイコンが欲しい

### ISSUE THREAD

**Issue by azu** [jser/jser.info#4]
https://twitter.com/jser_info に更新ログが流れるようにしてるけど、アイコンが設定されてないので不便

**Comment by azu** [comment]
https://github.com/jser のアイコンも同じように欲しい…

自分JavaScriptのイメージ的には、世間でよくみられる[黄色いアレ](https://github.com/voodootikigod/logo.js)じゃなくて、白ベースなイメージ。

![title](http://take.ms/BjPRp) 
タイトル文字を白ベースにしてたのはそういう理由だった気がするけど、適当に作ったのでそこまで愛着があるわけではない…

**Comment by qrg** [comment]
> 自分JavaScriptのイメージ的には、世間でよくみられる黄色いアレじゃなくて、白ベースなイメージ。

なんか考えてみるかなと思ったんですが、なるべく azu さんのイメージに近いほうがいいだろうと思うので、もし可能なら近いイメージや、キーワードの羅列があると助かります。多ければ多いほど良い。

**Comment by azu** [comment]
あんまり強くイメージしたロゴとかがないので、かなり曖昧なイメージしかないですね…。

クラウドワークスにそういえば、ロゴデザインのコンペの穴埋めがあったのを思い出したので、やってみました。
色に白とかグレーってロゴにあんまり向いてない気がするので無視していい気がします…

伝統的、先進的の意味が良くわからなかったのですが、崩したデザイン=先進的? という感じで入れてます。

![2014-08-24_18-10-00](https://cloud.githubusercontent.com/assets/19714/4023028/6def280a-2b6e-11e4-8191-7b9d4abaa7c3.jpg)

Logoshiで好きなタイプのフォント(Change Fontでランダムに変わる)のキャプチャしてみましたが、フォントはあまり太すぎたり、崩してたりするよりは普通な感じのが好きっぽいです。
- https://www.logoshi.com/draw

![2014-08-24_18-19-57](https://cloud.githubusercontent.com/assets/19714/4023047/d1dabb58-2b6f-11e4-92ff-0fd6209a4176.jpg)

![2014-08-24_18-20-21](https://cloud.githubusercontent.com/assets/19714/4023048/e056ceba-2b6f-11e4-955b-2d49bc0c37ca.jpg)

![2014-08-24_18-21-30](https://cloud.githubusercontent.com/assets/19714/4023050/094adab4-2b70-11e4-82ac-7146782dd18b.jpg)

ランダムで出てきましたが、これとか位置のバランスとフォント良くて結構好きです。(色とか謎記号は適当ですが)

![2014-08-24_18-28-10](https://cloud.githubusercontent.com/assets/19714/4023059/f829b9ca-2b70-11e4-8520-29d49b487987.jpg)

**Comment by azu** [comment]
### キーワード

JSer.info やる時意識するキーワード
- 公平
  - 間違いが含まれてる可能性がある記事はできるだけ避ける
  - 個人の意見が強すぎる場合も、内容自体がよくても避ける
  - これは [JSer.info 1年を迎えて](http://azu.github.io/slide/offline_study/jser_info.html#slide6) あたりで書いてる事ですね。 via [オフライン勉強会でJSer.info一周年について発表してきた - JSer.info](http://jser.info/post/15883533195/)
  - 偏り過ぎない
  - これは特定ブラウザに偏り過ぎないという意味も
- 客観的
- JavaScriptであれば言語は関係ない
- 継続
- 即時性
- まとめる
  - 単一の記事だとイマイチでも複数で合わせて紹介する
- 紹介 | 提案
- キーワード
  - 紹介するときに、キーワードとなるキーワードをできるだけ列挙する
- 期限
  - 週一更新するけど、記事の貯まりが良くなかったら1日ぐらいずらす

**Comment by azu** [comment]
<img width="500" alt="jser" src="https://cloud.githubusercontent.com/assets/19714/9025255/8dc4b46e-3938-11e5-9590-711094df24b2.png">

ふとこんな感じのデザインが合ってそうな気がした。
■が情報で、それがinfoに集まるイメージ。
(もうちょっとデータの流れをキレイにするべきだけど。赤なのは特に意味なくてコントラスト的に何色がいいんだろ…)
- http://monosnap.com/image/K1kYQtYs0IwXyAwQPgIMxH79jQNsOz.png

**Comment by azu** [comment]
ただとてもどっかで見たことがある感じがする

**Comment by azu** [comment]
[Josefin Slab](https://www.google.com/fonts/specimen/Josefin+Slab)

#4D5774
<img width="500" alt="pattern_b" src="https://cloud.githubusercontent.com/assets/19714/9460904/17788956-4b45-11e5-8da1-347d2b2243a2.png">

#C4E8F4
<img width="500" alt="pattern_a" src="https://cloud.githubusercontent.com/assets/19714/9460905/17823528-4b45-11e5-975f-bab17b8147c7.png">

**Comment by azu** [comment]
●のアクセントはいるのかどうか
<img width="500" alt="pattern_c" src="https://cloud.githubusercontent.com/assets/19714/9461748/a666373e-4b4b-11e5-82ee-68c984859d8c.png">

**Comment by azu** [comment]
○
<img width="500" alt="pattern_d" src="https://cloud.githubusercontent.com/assets/19714/9461875/b3fed792-4b4c-11e5-8279-9b12bcae2ef0.png">

**Comment by azu** [comment]
○を1x1 小さく
<img width="500" alt="pattern_e" src="https://cloud.githubusercontent.com/assets/19714/9461998/883e36a6-4b4d-11e5-95b7-c5378c7a7b0f.png">

**Comment by azu** [comment]
icon
<img width="180" alt="icon" src="https://cloud.githubusercontent.com/assets/19714/9462483/30651f68-4b51-11e5-9d98-73deff0c7cb6.png">

**Comment by azu** [comment]
![2015-08-25_21-17-58](https://cloud.githubusercontent.com/assets/19714/9466294/c74991da-4b6e-11e5-83ec-8c46efd1e086.jpg)
![2015-08-25_21-18-39](https://cloud.githubusercontent.com/assets/19714/9466311/e01528aa-4b6e-11e5-86f3-df6aee366443.jpg)

作ったものを入れてみた

**Comment by azu** [comment]
ファビコンはさすがにアイコン流用だと潰れる…

**Comment by azu** [comment]
[jser/media](https://github.com/jser/media) 画像とかpsdとかをおいた

**Comment by azu** [comment]
とりあえず当初の目的はできたのでこのissueはcloseします。
まだfaviconが足りてないですが、mediaの方のリポジトリにissueを立てました
- https://github.com/jser/media/issues/1
