### ISSUE TITLE
JSer.info 6周年 && 300回目記念イベント @ 1月15日(日)

### ISSUE THREAD

**Issue by azu** [jser/jser.info#89]
#[2011年01月16日](http://jser.info/post/2774561807/)にJSer.infoを始めてから、2017年1月16日(月)で6周年になります。

200回  #31 や 5周年 #54  のようなイベントをまたやりたいと思います。

趣旨: JSer.infoの記念という口実で集まってJavaScriptについて話すイベントです。

### イベント申し込み

- Conpassから申し込み: https://jser.connpass.com/event/46997/

### 開催日

2017年1月15日(日) 14:00 - 19:00ぐらい(おわるまで)

### 場所

[サイボウズ株式会社](http://cybozu.co.jp/company/info/) 東京オフィス
[アクセスマップ | サイボウズ株式会社](https://cybozu.co.jp/company/access/ "アクセスマップ | サイボウズ株式会社")
東京都中央区日本橋2-7-1 東京日本橋タワー 27階

会場管理者: @teppeis 

### 人数

-  70 ~ 90人ぐらいの予定(会場の限界は90人)

### 内容

- [x] 通常の発表枠
- [x] Discussion
  - 質問ボード: [JSer.info 6周年 - JavaScript Discussion](https://app.sli.do/event/bkry5ojl/ask "JSer.info 6周年 - JavaScript Discussion")
- [x] LTとか

内容はいつもどおりJavaScriptならごちゃごちゃでいいと思います。

## TODO
- [x] イベントページ
- [x] 何するのかを決める
- [x] 呼んで欲しい人
- [ ] 手伝ってくれる人への通知

## CoC

- 公平な心をもって議論しましょう
- 写真の撮影/アップロードなどは写ってる人に許可を貰ってから行いましょう
- スポンサーセッションはできません(会場案内とセットなら問題ありません)

## その他

連絡や意見はこのIssueかGitterへ。

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/jser/jser.info?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

<del>参加したいなーと思う人は 👍 のリアクションを付けておくと良さそう。</del>

**Comment by ahomu** [comment]
Twitter で話していた弊社セミナールームの件、一応ご参考までに。

片側のスクリーンが中央にくるよう机・椅子をレイアウトして
使ってない側にはパーティションを配置すればうまくいきそうです。

<img width="659" alt="図面的な何か" src="https://cloud.githubusercontent.com/assets/404356/19932855/d9b0c324-a154-11e6-8e4a-26a09e03ee22.png">
※ 私が喋ってた狭いほうでなくて、もう片方の広いほうの部屋です

もし懇親会などを予定されるのでしたら、
使ってない側に🍕🍣を配備しておくとかするとスムーズな感じです。

**Comment by azu** [comment]
@ahomu なるほどー。
人数的には 6 \* 8 〜ぐらいですかね。(いざとなったらスケールできそうで良さそう)

> もし懇親会などを予定されるのでしたら、

あってもなくても大丈夫ですが、会場的にOKならやりたいぐらいの感じです。
例年、後半は懇談会しながらずっと勝手に発表してろ的な感じになります。

**Comment by ahomu** [comment]
@azu 
図面の赤枠で囲った範囲だと、人数は 6 \* 8 \* 2 で MAX 96 人想定ですね。
裏技で、椅子だけ並べるスタイルにすると無限に密度が高まります。（肩を寄せ合って議論するならアリ？）
会場スポンサー的には懇親会もたぶん手配出来ます。

**Comment by azu** [comment]
@ahomu なるほど。良さそうです。
(募集の限界が96で、実際には70人前後ぐらいになるとちょうどいいかなと考えています)
2017年1月14日(土) か2017年1月15日(日)あたりが可能ならばお願いしたいです。
懇談会を入れると 14:00 - 19:00 または 20:00ぐらいですかね。

**Comment by ahomu** [comment]
@azu 
委細承知です。次営業日（金曜）に施設予約状況の照会してみますね。

**Comment by tetsuharuohzeki** [comment]
緑のマークシティ企業がダメだった場合に備えて, フォールバック先候補の情報提供しておきますね

## 立地
- [渋谷の道玄坂の上, 渋谷ファースプレイス8F, VOYAGE GROUP](https://www.google.co.jp/maps/place/%E3%80%92150-0045+T%C5%8Dky%C5%8D-to,+Shibuya-ku,+Shinsench%C5%8D,+8%E2%88%9216,+%E6%B8%8B%E8%B0%B7%E3%83%95%E3%82%A1%E3%83%BC%E3%82%B9%E3%83%88%E3%83%97%E3%83%AC%E3%82%A4%E3%82%B9/@35.6668526,139.6926262,14z/data=!3m1!4b1!4m13!1m7!3m6!1s0x60188b55a7e6d7b5:0xaff179d1e13cec4!2z44CSMTUwLTAwNDUgVMWNa3nFjS10bywgU2hpYnV5YS1rdSwgU2hpbnNlbmNoxY0sIDjiiJIxNiwg5riL6LC344OV44Kh44O844K544OI44OX44Os44Kk44K5!3b1!8m2!3d35.6552616!4d139.6937299!3m4!1s0x60188b55a7e6d7b5:0xaff179d1e13cec4!8m2!3d35.6552616!4d139.6937299)
- 最寄り駅
  - 渋谷駅: 徒歩5~10分
  - 京王井の頭線, 神泉駅: 徒歩5分

## 会場詳細
- だいたい100人くらいまでいけます
- ゲストWifiあります
- 電源あります
- 酒スポンサー可能なはず
- 飯スポンサーは要確認

### 制約事項
- 会場スポンサーとして案内と合わせて簡単なhiringの案内をする必要があるかもしれないです
  - 飯スポンサーまでやった場合は必須だった記憶
- ビルの出入り口に鍵がかかってるので, 遅刻者pick upには制約があります

### 可能な日程
- 2017, Jan 14th (Sat.)
  - 15:00~21:00ぐらいまで可
  - この日は直前に[Tokyo iOS Meetup](http://www.meetup.com/ja-JP/TokyoiOSMeetup/events/234405181/)があるので, 14:00から開始は難しいです
- 2017, Jan 15th (Sun.)
  - 14:00~21:00ぐらいまで可

---

他は某サイ*ウズの本部長に頼るとかですかねェ……

**Comment by teppeis** [comment]
会場提供できますよ。
前回と同じセミナールーム(90人)か、もっと少人数(30～40人)で飲み食いしながら議論中心にやりたいならbikeshed.jsとかで使ったBARもあります。
フォールバックとしてどうぞ。（と言っても予約は1か月前までが安心）

**Comment by ahomu** [comment]
@azu 
ごめんなさい！ 諸事情で今の時点で施設利用 NG でした... orz
（最終 OK になるかもしれないけど、確定が遅れてしまいそう）
自分から言い出したわりに申し訳ないです :bow:

フォールバック先のご提案が他からもあって良かった。:pray:

**Comment by azu** [comment]
@ahomu 💚

**Comment by azu** [comment]
@saneyuki @teppeis どうしましょうか。
個人的には、ピックアップ要員とかそういうのがない方が楽でいいですね。
(懇談会費用は参加者とか自分のプールしてるOSS貯金から出せばいいのであんまり考えなくて良さそう)

まあ、まだ2ヶ月以上先の話なので、1ヶ月ぐらい前に決まっていればいいかなーという感じですね。
(イベントの募集開始も多分1ヶ月ぐらい前かな)

**Comment by teppeis** [comment]
@azu 現時点で弊社は、2017年1月14日(土) は空いて無くて、2017年1月15日(日) は空いてます（セミナールーム、BARともに）。

**Comment by tetsuharuohzeki** [comment]
@azu 

両日程ともに、仮押さえ済みです

**Comment by azu** [comment]
@teppeis 自分の中では15日(日)優先だったので、ちょうどよさそう。
(慣れているので) サイボウズ社さんにお願いします！

``` js
> (Math.random() < 0.5) ? "某サイボウズ" : "渋谷の道玄坂の上"
"某サイボウズ"
```

@saneyuki 🙇

**Comment by teppeis** [comment]
@azu 90人と40人、どっちにします？

**Comment by azu** [comment]
@teppeis 90人

**Comment by teppeis** [comment]
@azu 1月15日（日）13:00 ～ 22:00 いつものセミナールーム(Max90名)で部屋を確保しました。

**Comment by azu** [comment]
@teppeis ありがとうございます！

開催日確定したので何するかを考えないとなー

**Comment by uyeong** [comment]
👍

**Comment by azu** [comment]
@teppeis https://connpass.com/event/46997/edit/
イベントのページ作りました。会場周り何かあれば更新よろしくお願いします。

**Comment by azu** [comment]
https://jser.connpass.com/event/46997/
イベントのページを公開しました。
募集開始は2016/12/15(木)から

**Comment by azu** [comment]
[2017年1月15日(日)に JSer.info 6周年 && 300回目記念イベント を開催します - JSer.info](https://jser.info/2016/12/13/announcement-jser-info-6years-event/ "2017年1月15日(日)に JSer.info 6周年 &amp;&amp; 300回目記念イベント を開催します - JSer.info")
告知を書きました。
あとはスライドを書こう。

発表枠で申し込んだ人はこのIssueに、希望の発表時間とタイトル(仮でもいい)を書き込んでください。

**Comment by makotokato** [comment]
発表枠申し込みました。発表内容は、"ECMA-402を知ってますか？" で、15分でお願いします。(20分でも可能ですがちょっと余るかも)

**Comment by youchan** [comment]
発表枠申し込みました。時間は決めていないので15分でも20分でも決めていただけたらと思います。
内容はOpal(Ruby to JavaScript compiler)についてです。
仮のタイトルは「Opalのすすめ」でお願いします。
内容がRubyよりの話になりますので適切かどうかわかりません。不適切であればとりさげます。

**Comment by azu** [comment]
@makotokato @youchan 了解ですー。
15分発表 + 5分質疑に設定して、合計で20分にしましょう。

**Comment by potato4d** [comment]
@azu
ご連絡遅くなって申し訳ございません！内容ですが、以下でお願いいたします！

タイトル：2017年のJavaScriptとフロントエンドの楽しみ方
時間　　：15分を希望
概要　　：「最近遅い」「以前までの楽しさが減った」と言われるフロントエンドとJavaScriptについて、2017年の楽しみかた、ただSPAを作るだけでイケていた時代の先について話す予定です。

**Comment by azu** [comment]
@potato4d 反映しました(15分 + 5分質疑にしてます)

**Comment by azu** [comment]
明日のイベント用カンニングペーパーです。
サマリをまとめた。

ハッシュタグ: [#jserinfo](https://twitter.com/search?q=%23jserinfo)

## 人

- 参加枠
  - 70人
  - 補欠
    - 現在補欠でも、どうしても参加したい場合は来てもらって問題ないことを通知
    - 最大25人(当日キャンセルを含めると会場キャパシティ 90人なのでいけるかな)
- 海外ゲスト: @UYEONG さん(ヨンジュさん)
  - 合計: 3人
- 翻訳手伝い
  - @song さん

## イベント進行

- [JSer.info 6周年と300回記念イベント - connpass](https://jser.connpass.com/event/46997/ "JSer.info 6周年と300回記念イベント - connpass")を確認
- 開場
  - 13:30 から
- 閉場
  - 20:00に閉会
  - 21:00に撤収
  - 22:00が会場的な〆切
- 参加費
  - 参加枠の人は 1000円
  - 途中の休憩時間で回収?
  - お手伝い枠: @TomoyaShibata さん @potato4d さん
  - JavaScript Discussion開始するぐらいに発注?
- 議事録
  - Dropbox Paperを使う
  - https://paper.dropbox.com/doc/JSer.info-6-4ko0NvdzqpYj5Rt6TvdJi
  - リアルタイムに議事録を取る
- JavaScript Disscussion
  - 場所: https://slido.com#jserinfo を使う
  - 当日に20分ぐらい時間取る(休憩時間)

**Comment by azu** [comment]
無事終了しました。

- [JSer.info 6周年記念イベントを開催しました - JSer.info](https://jser.info/2017/01/15/jser-info-6years/ "JSer.info 6周年記念イベントを開催しました - JSer.info")

お疲れ様でした！
